resolver: lts-9.21

packages:
- .

extra-deps:
  - accelerate-1.2.0.0
  - accelerate-llvm-ptx-1.2.0.0
  - accelerate-llvm-1.2.0.0
  - 'cuda-0.9.0.3'
  - 'nvvm-0.8.0.3'
  - hashtables-1.2.3.1
  - tasty-hedgehog-0.2.0.0

flags:
  llvm-hs:
    shared-llvm: true
  accelerate:
    debug: true
    nofib: false
