resolver: lts-9.21

packages:
- .

extra-deps:
  # - accelerate-1.2.0.0
  # - accelerate-llvm-ptx-1.2.0.0
  # - accelerate-llvm-1.2.0.0
  - git:    https://github.com/tmcdonell/accelerate.git
    commit: 442dcbdb8d95407bc650d8f4ce6aa62ab593e484

  - git:    https://github.com/tmcdonell/accelerate-llvm.git
    commit: 6aacde0ffae37552f5f5bacd1ae3029b14012f8c
    subdirs:
      - 'accelerate-llvm'
      - 'accelerate-llvm-native'
      - 'accelerate-llvm-ptx'
  - 'cuda-0.9.0.3'
  - 'nvvm-0.8.0.3'
  - hashtables-1.2.3.1
  - tasty-hedgehog-0.2.0.0
  - half-0.3

flags:
  llvm-hs:
    shared-llvm: true
  accelerate:
    debug: true
    nofib: false
